txt_firstname="id:firstName"
txt_lastname="id:lastName"
txt_emailid="id:userEmail"
select_gender="//*[@id='gender-radio-2']"
txt_mobilenum="xpath://input[@id='userNumber']"
txt_DOB="xpath://*[@id='dateOfBirth']/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div[3]"
txt_subjects="xpath://div[@class='subjects-auto-complete__value-container subjects-auto-complete__value-container--is-multi css-1hwfws3']"
select_hobbies="id:hobbies-checkbox-3"
upload_picture="xpath://input[@id='uploadPicture']"
txt_curraddress="id:currentAddress"
